# Generated by Django 4.1.3 on 2022-12-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='e_cash',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
